<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-VHFI0LE" failures="2" tests="4" name="PetTests" time="8.857" errors="0" timestamp="2025-03-15T00:00:10 IST">
  <testcase classname="api.test.UserTests2" name="testPostUser" time="3.038"/>
  <testcase classname="api.test.UserTests2" name="testGetUserByName" time="1.198">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests2.testGetUserByName(UserTests2.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.UserTests2" name="updateUserByName" time="2.342"/>
  <testcase classname="api.test.UserTests2" name="deleteUserByName" time="1.25">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests2.deleteUserByName(UserTests2.java:98)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteUserByName -->
</testsuite> <!-- PetTests -->
